import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const source = resolve(process.argv[2] || join(root, '..', 'public'));
const target = join(root, 'public');
// Intentionally excludes premium-nav.js (it mounts a production enquiry integration), API code and analytics.
const files = [
  'design-system.css', 'premium-nav.css', 'journey.css', 'journey.js', 'shared-footer.css',
  'ae-logo.webp', 'assets/ae-logo-FINAL-nb.png', 'favicon.png', 'cta-float.webp', 'cta-reach-arm.png',
  'assets/worlds/systems-mascot-v2.webp', 'assets/worlds/agents.webp',
  'assets/worlds/plugins-mascot-v2.webp', 'assets/worlds/products-mascot-v2.webp',
  'fonts/inter-latin.woff2', 'fonts/space-grotesk-latin.woff2',
];
// Bind the site's literal colours to template tokens while keeping the original values as fallbacks.
const tokens = {
  '#f7f8f6': 'paper', '#111719': 'ink', '#0c1016': 'ink', '#15191c': 'ink', '#101619': 'ink',
  '#687178': 'muted', '#697178': 'muted', '#737b7d': 'muted', '#505a61': 'muted',
  '#d9dcda': 'line', '#d9dedf': 'line', '#cdd2cf': 'line', '#e4e7e4': 'ghost',
  '#b73512': 'accent', '#ff6338': 'accent-bright', '#165bcc': 'focus', '#eef1ef': 'surface',
};
for (const file of files) {
  const output = join(target, file);
  await mkdir(dirname(output), { recursive: true });
  if (!file.endsWith('.css')) { await copyFile(join(source, file), output); continue; }
  const css = (await readFile(join(source, file), 'utf8'))
    .replace(/url\(['"]?\/([^)'"\s]+)['"]?\)/g, "url('./$1')")
    .replace(/#[0-9a-f]{6}\b/gi, color => tokens[color.toLowerCase()] ? `var(--template-${tokens[color.toLowerCase()]},${color})` : color);
  await writeFile(output, `/* Generated by template/sync.mjs from public/${file}. Edit the source or template-overrides.css. */\n${css}`);
}
console.log(`Synced ${files.length} allowlisted design files from ${source}.`);
