/**
 * ConfigGenerator - Configuration generation and export system
 * Generates different format configurations from selected components
 */

export class ConfigGenerator {
    constructor() {
        this.templates = this.initializeTemplates();
    }

    initializeTemplates() {
        return {
            json: {
                header: 'Configuration File Generated by AE Component Gallery',
                format: 'json'
            },
            js: {
                header: '// Component Configuration Generated by AE Component Gallery',
                format: 'javascript',
                imports: [],
                exports: true
            },
            css: {
                header: '/* CSS Custom Properties Generated by AE Component Gallery */',
                format: 'css',
                rootSelector: ':root'
            },
            html: {
                header: '<!-- HTML Template Generated by AE Component Gallery -->',
                format: 'html',
                includeScripts: true
            }
        };
    }

    /**
     * Generate configuration in the specified format
     */
    generateConfiguration(selectedComponents, format = 'json') {
        if (!selectedComponents || selectedComponents.length === 0) {
            return this.getEmptyConfig(format);
        }

        switch (format) {
            case 'json':
                return this.generateJSONConfig(selectedComponents);
            case 'js':
                return this.generateJSConfig(selectedComponents);
            case 'css':
                return this.generateCSSConfig(selectedComponents);
            case 'html':
                return this.generateHTMLConfig(selectedComponents);
            default:
                return this.generateJSONConfig(selectedComponents);
        }
    }

    /**
     * Generate JSON configuration
     */
    generateJSONConfig(selectedComponents) {
        const config = {
            metadata: {
                generated: new Date().toISOString(),
                version: '1.0.0',
                componentCount: selectedComponents.length
            },
            components: {}
        };

        selectedComponents.forEach(component => {
            config.components[component.id] = {
                name: component.name,
                enabled: true,
                variation: component.variation || 0,
                config: component.config || {}
            };
        });

        return JSON.stringify(config, null, 2);
    }

    /**
     * Generate JavaScript module configuration
     */
    generateJSConfig(selectedComponents) {
        const imports = [];
        const configObjects = [];
        const componentExports = [];

        selectedComponents.forEach((component, index) => {
            // Generate import statement
            imports.push(`import { ${component.name.replace(/\s+/g, '')} } from './components/${component.id}.js';`);

            // Generate config object
            const configVar = `${component.id.replace(/-/g, '')}Config`;
            configObjects.push(`
const ${configVar} = {
    enabled: true,
    variation: ${component.variation || 0},
    config: ${JSON.stringify(component.config || {}, null, 4)}
};`);

            // Generate export
            componentExports.push(`    ${configVar}: ${configVar}`);
        });

        return `${this.templates.js.header}

// Imports
${imports.join('\n')}

// Component Configurations
${configObjects.join('\n')}

// Export all configurations
export const componentConfig = {
${componentExports.join(',\n')}
};

// Initialize components with their configurations
export function initializeComponents() {
    const components = [];

    ${selectedComponents.map((component, index) => `
    // Initialize ${component.name}
    if (componentConfig.${component.id.replace(/-/g, '')}Config.enabled) {
        const ${component.id.replace(/-/g, '')}Instance = new ${component.name.replace(/\s+/g, '')}(
            document.body,
            componentConfig.${component.id.replace(/-/g, '')}Config.config
        );
        components.push({
            id: '${component.id}',
            instance: ${component.id.replace(/-/g, '')}Instance
        });
    }`).join('')}

    return components;
}

// Default export
export default {
    config: componentConfig,
    initialize: initializeComponents
};`;
    }

    /**
     * Generate CSS custom properties configuration
     */
    generateCSSConfig(selectedComponents) {
        const cssVars = [];

        selectedComponents.forEach(component => {
            const componentId = component.id.replace(/-/g, '-');

            // Add main component variables
            cssVars.push(`    /* ${component.name} Component */`);
            cssVars.push(`    --${componentId}-enabled: ${component.enabled !== false ? 'true' : 'false'};`);
            cssVars.push(`    --${componentId}-variation: ${component.variation || 0};`);

            // Add configuration properties
            if (component.config) {
                Object.entries(component.config).forEach(([key, value]) => {
                    const cssVar = this.convertToCSSVar(key, value);
                    cssVars.push(`    --${componentId}-${cssVar.name}: ${cssVar.value};`);
                });
            }

            cssVars.push(''); // Empty line for readability
        });

        return `${this.templates.css.header}

${this.templates.css.rootSelector} {
${cssVars.join('\n')}
}

/* Component-specific styles based on configuration */
${selectedComponents.map(component => this.generateComponentCSS(component)).join('\n\n')}`;
    }

    /**
     * Convert configuration key and value to CSS custom property
     */
    convertToCSSVar(key, value) {
        // Convert camelCase to kebab-case
        const cssName = key.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, '$1-$2').toLowerCase();

        // Convert value to CSS-compatible format
        let cssValue = value;
        if (typeof value === 'boolean') {
            cssValue = value ? '1' : '0';
        } else if (typeof value === 'number') {
            cssValue = value.toString();
        } else if (typeof value === 'string') {
            // Keep string values as-is (colors, etc.)
        }

        return { name: cssName, value: cssValue };
    }

    /**
     * Generate component-specific CSS
     */
    generateComponentCSS(component) {
        const componentId = component.id.replace(/-/g, '-');
        let css = `/* ${component.name} Component Styles */
.${componentId}-container {
    display: var(--${componentId}-enabled, true) == 'true' ? block : none;
}`;

        if (component.config) {
            // Generate style overrides based on configuration
            if (component.config.color) {
                css += `
.${componentId}-container {
    --primary-color: ${component.config.color};
}`;
            }

            if (component.config.backgroundColor) {
                css += `
.${componentId}-container {
    background-color: ${component.config.backgroundColor};
}`;
            }

            if (component.config.size) {
                css += `
.${componentId}-container {
    --component-size: ${component.config.size}px;
}`;
            }
        }

        return css;
    }

    /**
     * Generate HTML template configuration
     */
    generateHTMLConfig(selectedComponents) {
        const componentScripts = [];
        const componentHTML = [];

        selectedComponents.forEach(component => {
            // Generate script tags
            componentScripts.push(`    <script src="js/components/${component.id}.js"></script>`);

            // Generate initialization script
            const configVar = `${component.id.replace(/-/g, '')}Config`;
            componentHTML.push(`
        <!-- ${component.name} Component -->
        <div id="${component.id}-container" class="component-container ${component.id}-container" data-component-config="${configVar}">
        </div>`);
        });

        const initializationScript = `
    <script>
        // Component configurations
        const componentConfigs = ${JSON.stringify(selectedComponents.reduce((acc, comp) => {
            acc[comp.id] = comp.config || {};
            return acc;
        }, {}), null, 8)};

        // Initialize components when DOM is ready
        document.addEventListener('DOMContentLoaded', function() {
            ${selectedComponents.map(component => {
                const className = component.name.replace(/\s+/g, '');
                return `
            // Initialize ${component.name}
            if (document.getElementById('${component.id}-container')) {
                try {
                    new ${className}('#${component.id}-container', componentConfigs['${component.id}']);
                } catch (error) {
                    console.error('Failed to initialize ${component.name}:', error);
                }
                }`;
            }).join('')}
        });
    </script>`;

        return `${this.templates.html.header}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AE Components - Generated Configuration</title>

    <!-- External Dependencies -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet">

    <!-- Application Styles -->
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/components.css">
    <link rel="stylesheet" href="css/gallery.css">
</head>
<body class="bg-dark-bg text-gray-200 min-h-screen">
    <!-- Component Container -->
    <div id="app-container">
        <!-- Header -->
        <header class="p-6 border-b border-white/10">
            <h1 class="text-2xl font-bold text-white">AE Components Showcase</h1>
            <p class="text-gray-400">Interactive components generated from configuration</p>
        </header>

        <!-- Components -->${componentHTML.join('')}

    </div>

    <!-- Component Scripts -->
${componentScripts.join('\n')}

${initializationScript}

</body>
</html>`;
    }

    /**
     * Generate comparison report
     */
    generateComparisonReport(comparisonComponents) {
        let report = `COMPONENT COMPARISON REPORT
Generated: ${new Date().toLocaleString()}
========================================

`;

        if (comparisonComponents.length === 0) {
            report += 'No components selected for comparison.\n';
            return report;
        }

        // Overview
        report += `OVERVIEW
---------
Components being compared: ${comparisonComponents.length}

`;

        // Component details
        comparisonComponents.forEach((comp, index) => {
            report += `${index + 1}. ${comp.component.name}
   Category: ${comp.component.category}
   Description: ${comp.component.description}
   Tags: ${comp.component.tags.join(', ')}
   Variations: ${comp.component.variations.length}

`;
        });

        // Feature comparison
        report += `FEATURE COMPARISON
================

`;

        const features = [
            'Configurable Options',
            'Multiple Variations',
            'Visual Customization',
            'Interactive Elements',
            'Animation Support'
        ];

        features.forEach(feature => {
            report += `${feature}:\n`;
            comparisonComponents.forEach((comp, index) => {
                const supported = this.hasFeature(comp.component, feature);
                report += `   ${index + 1}. ${comp.component.name}: ${supported ? '✓' : '✗'}\n`;
            });
            report += '\n';
        });

        // Configuration comparison
        report += `CONFIGURATION COMPARISON
========================

`;

        const allConfigs = comparisonComponents.map(comp => ({
            name: comp.component.name,
            config: comp.component.variations[comp.variation].config
        }));

        // Find all unique config keys
        const allKeys = new Set();
        allConfigs.forEach(c => Object.keys(c.config).forEach(key => allKeys.add(key)));

        Array.from(allKeys).forEach(key => {
            report += `${key}:\n`;
            allConfigs.forEach((config, index) => {
                const value = config.config[key] || 'N/A';
                report += `   ${index + 1}. ${config.name}: ${JSON.stringify(value)}\n`;
            });
            report += '\n';
        });

        // Recommendations
        report += `RECOMMENDATIONS
===============

`;

        const recommendations = this.generateRecommendations(comparisonComponents);
        report += recommendations.join('\n') + '\n\n';

        // Usage scenarios
        report += `USAGE SCENARIOS
================

${this.generateUsageScenarios(comparisonComponents).join('\n\n')}

`;

        // Conclusion
        report += `CONCLUSION
===========
This comparison provides insights into the capabilities and configurations of the selected components.
Consider your specific requirements and use cases when selecting components for your application.

Generated by AE Component Gallery
https://ae.foundation/components
`;

        return report;
    }

    /**
     * Check if component has specific feature
     */
    hasFeature(component, feature) {
        const featureMap = {
            'Configurable Options': !!component.configSchema,
            'Multiple Variations': component.variations && component.variations.length > 1,
            'Visual Customization': component.configSchema &&
                Object.values(component.configSchema).some(schema => schema.type === 'color'),
            'Interactive Elements': component.category === 'interactive',
            'Animation Support': component.tags && component.tags.includes('animation')
        };

        return featureMap[feature] || false;
    }

    /**
     * Generate recommendations based on comparison
     */
    generateRecommendations(comparisonComponents) {
        const recommendations = [];

        // Analyze component categories
        const categories = comparisonComponents.map(comp => comp.component.category);
        const uniqueCategories = [...new Set(categories)];

        if (uniqueCategories.length > 1) {
            recommendations.push('• Consider mixing components from different categories for rich user experiences');
        }

        // Analyze configuration complexity
        const configCounts = comparisonComponents.map(comp =>
            Object.keys(comp.component.variations[comp.variation].config).length
        );
        const avgConfigCount = configCounts.reduce((a, b) => a + b, 0) / configCounts.length;

        if (avgConfigCount > 5) {
            recommendations.push('• Components offer extensive customization - plan configuration strategy');
        }

        // Check for interactive components
        const interactiveCount = comparisonComponents.filter(comp =>
            comp.component.category === 'interactive'
        ).length;

        if (interactiveCount > 0) {
            recommendations.push('• Interactive components detected - ensure proper event handling and user experience');
        }

        // Performance considerations
        if (comparisonComponents.some(comp =>
            comp.component.tags && comp.component.tags.includes('animation')
        )) {
            recommendations.push('• Animated components present - consider performance optimization and animation controls');
        }

        return recommendations;
    }

    /**
     * Generate usage scenarios based on component comparison
     */
    generateUsageScenarios(comparisonComponents) {
        const scenarios = [];

        // Dashboard scenario
        const hasBackgrounds = comparisonComponents.some(comp => comp.component.category === 'background');
        const hasUI = comparisonComponents.some(comp => comp.component.category === 'ui');

        if (hasBackgrounds && hasUI) {
            scenarios.push('Dashboard/Control Panel: Combine background components with UI elements for data visualization dashboards');
        }

        // Interactive application scenario
        const hasInteractive = comparisonComponents.some(comp => comp.component.category === 'interactive');

        if (hasInteractive) {
            scenarios.push('Interactive Applications: Leverage interactive components for user engagement and dynamic experiences');
        }

        // Loading experience scenario
        const hasUtility = comparisonComponents.some(comp => comp.component.category === 'utility');

        if (hasUtility) {
            scenarios.push('Loading Experiences: Use utility components like preloaders for smooth user experience during content loading');
        }

        // Showcase scenario
        if (comparisonComponents.length >= 3) {
            scenarios.push('Component Showcase: Create comprehensive demonstrations using multiple component types and variations');
        }

        return scenarios;
    }

    /**
     * Get empty configuration for specified format
     */
    getEmptyConfig(format) {
        switch (format) {
            case 'json':
                return JSON.stringify({
                    metadata: {
                        generated: new Date().toISOString(),
                        version: '1.0.0',
                        componentCount: 0
                    },
                    components: {}
                }, null, 2);

            case 'js':
                return `${this.templates.js.header}

// No components selected
export const componentConfig = {};

export function initializeComponents() {
    return [];
}

export default {
    config: componentConfig,
    initialize: initializeComponents
};`;

            case 'css':
                return `${this.templates.css.header}

${this.templates.css.rootSelector} {
    /* No components selected */
}`;

            case 'html':
                return `${this.templates.html.header}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>No Components Selected</title>
</head>
<body>
    <h1>No components selected for configuration</h1>
</body>
</html>`;

            default:
                return 'No configuration available';
        }
    }
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ConfigGenerator;
}